In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("2.csv")

In [3]:
df.head()

id      genres1      genres2      genres3
0  40464      Romance       Comedy       Comedy
1  41406       Horror       Horror       Horror
2  70683  Documentary  Documentary  Documentary
3  34806       Comedy       Comedy       Comedy
4  64944      Romance        Drama        Drama

In [4]:
df['genres1'].unique()

array(['Romance', 'Horror', 'Documentary', 'Comedy', 'Action', 'Drama',
       'Thriller', 'Sci-Fi', 'Adventure', 'Crime'], dtype=object)

In [5]:
d={'Comedy':0, 'Romance':1, 'Documentary':2, 'Action':3, 'Horror':4, 'Thriller':5,
       'Drama':6, 'Sci-Fi':7, 'Adventure':8, 'Crime':9}
df['genres1']=df['genres1'].map(d)
df.head()

id  genres1      genres2      genres3
0  40464        1       Comedy       Comedy
1  41406        4       Horror       Horror
2  70683        2  Documentary  Documentary
3  34806        0       Comedy       Comedy
4  64944        1        Drama        Drama

In [6]:

df['genres2']=df['genres2'].map(d)
df['genres3']=df['genres3'].map(d)

df.head()


id  genres1  genres2  genres3
0  40464        1        0        0
1  41406        4        4        4
2  70683        2        2        2
3  34806        0        0        0
4  64944        1        6        6

In [7]:
X=df.drop(columns=['id'])

In [14]:
y=np.bincount(X).argmax()

ValueError: object too deep for desired array

In [8]:
X=np.array(X)

In [9]:
X

array([[1, 0, 0],
       [4, 4, 4],
       [2, 2, 2],
       ...,
       [6, 6, 6],
       [0, 8, 8],
       [0, 2, 2]])

In [10]:
from scipy import stats
m=stats.mode(X.T)

In [11]:
n=np.array(m)
a=n[0][0]

In [12]:
z=np.array(df["id"])

In [13]:
z

array([40464, 41406, 70683, ..., 63854, 34816,  7447])

In [14]:
o=np.vstack((z,a)).T

In [15]:
o

array([[40464,     0],
       [41406,     4],
       [70683,     2],
       ...,
       [63854,     6],
       [34816,     8],
       [ 7447,     2]])

In [16]:
data=pd.DataFrame(o)
data.head()

0  1
0  40464  0
1  41406  4
2  70683  2
3  34806  0
4  64944  6

In [17]:
f={0:'Comedy', 1:'Romance', 2:'Documentary',3: 'Action',4: 'Horror',5: 'Thriller',
       6:'Drama',7: 'Sci-Fi',8: 'Adventure', 9:'Crime'}
data[1]=data[1].map(f)

In [18]:
data.head()

0            1
0  40464       Comedy
1  41406       Horror
2  70683  Documentary
3  34806       Comedy
4  64944        Drama

In [20]:
data.to_csv('sample_submission_cv3.csv',index=False)